#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
图2 工作流图：专用网格布局生成器
彻底避免"AI 手摆坐标"导致的重叠/压框/不对齐问题。
所有坐标由 Python 按固定网格规则自动计算，输出 TikZ 内联 LaTeX。
"""
import os
import sys
from dataclasses import dataclass
from typing import List, Tuple

# --------------------------- 图的逻辑描述（只改这里） ---------------------------
@dataclass
class NodeSpec:
    text: str          # 节点文字（允许 \\n 换行）
    width_cm: float    # 节点宽度（cm）

@dataclass
class ColumnSpec:
    title: str
    fill: str          # panel 背景灰度，如 "gray!18"
    penwidth: float
    nodes: List[NodeSpec]

COLUMNS = [
    ColumnSpec(
        title=r"\textbf{阶段 1}\\[-4pt] 学情 / 案情输入",
        fill="gray!18", penwidth=0.5,
        nodes=[
            NodeSpec(r"\textbf{选择实验}\\ Lab（1–4）", 2.4),
            NodeSpec(r"\textbf{提交案情 / 启动研判}", 2.4),
            NodeSpec(r"\textbf{失败场景诚实反思}", 2.4),
        ],
    ),
    ColumnSpec(
        title=r"\textbf{阶段 2}\\[-4pt] FraudLens 系统内核",
        fill="gray!25", penwidth=0.7,
        nodes=[
            NodeSpec(r"\textbf{预处理}\\ 案情清洗 / 字段对齐", 3.3),
            NodeSpec(r"\textbf{BGE 嵌入 + HAN 构图}\\ 语义 / 结构双通道", 3.3),
            NodeSpec(r"\textbf{LangGraph 反思闭环}\\[-1pt]\scriptsize plan→preprocess\\[-3pt]\scriptsize analyze→cluster→reflect", 3.3),
        ],
    ),
    ColumnSpec(
        title=r"\textbf{阶段 3}\\[-4pt] 人机协同决策",
        fill="gray!18", penwidth=0.5,
        nodes=[
            NodeSpec(r"\textbf{规则 vs AI 建议对比}\\ Lab1 / Lab2", 2.8),
            NodeSpec(r"\textbf{冻卡决策与伦理权衡}\\ Lab3", 2.8),
            NodeSpec(r"\textbf{边界认知与诚实反思}\\ Lab4", 2.8),
        ],
    ),
]

# 布局参数（单位：cm）
NODE_HEIGHT   = 1.40          # 所有节点等高
NODE_VGAP     = 0.60          # 列内节点垂直间距
COL_HGAP      = 3.50          # 列中心之间的水平间距
PANEL_PAD     = 0.40          # panel 内边距
BAR_HEIGHT    = 0.65          # 底部审计条高度
BAR_VGAP      = 0.75          # panel 底边到 audit bar 顶边
BAR_EXTRA_W   = 0.30          # bar 宽度比三列总宽多出的部分

# TikZ 风格
TEX_TEMPLATE = r"""%% Auto-generated by build_fig_workflow.py
%% DO NOT hand-edit coordinates; edit the Python script instead.
\documentclass[tikz,border=0pt]{standalone}
\usepackage{ctex}
\usepackage{tikz}
\usetikzlibrary{positioning,fit,backgrounds,calc,arrows.meta}
\begin{document}
\begin{tikzpicture}[
  >=Stealth,
  node distance=0cm,
  cell/.style={{
    draw=black, line width=0.5pt, rounded corners=3pt, fill=white,
    minimum width=%(node_w)scm, minimum height=%(node_h)scm,
    align=center, font=\footnotesize, inner sep=2.5pt, text width=%(text_w)scm
  }},
  title/.style={{
    font=\footnotesize\bfseries, text=black, align=left, anchor=south west
  }},
  bar/.style={{
    draw=black, line width=0.5pt, rounded corners=3pt, fill=gray!30,
    minimum width=%(bar_w)scm, minimum height=%(bar_h)scm,
    align=center, font=\footnotesize, text width=%(bar_text_w)scm
  }},
  smalllabel/.style={{
    font=\scriptsize, fill=white, inner sep=2pt, rounded corners=2pt,
    draw=black, line width=0.4pt
  }},
  arrow/.style={{
    ->, line width=0.7pt, color=black
  }},
  dasharrow/.style={{
    ->, line width=0.7pt, color=black, dashed
  }}
]

%(nodes_code)s

%(panels_code)s

%(edges_code)s

\end{tikzpicture}
\end{document}
"""

def fmt(f: float) -> str:
    return f"{f:.3f}"

def tex_escape(s: str) -> str:
    return s

def main():
    n_rows = len(COLUMNS[0].nodes)
    # 统一行高内所有节点尺寸一致
    # 计算每列中心 x 坐标（中列在 x=0）
    centers_x = []
    cur = -COL_HGAP
    for _ in COLUMNS:
        centers_x.append(cur)
        cur += COL_HGAP

    # 节点 y 坐标：从顶部开始向下排，整体垂直居中
    total_h = n_rows * NODE_HEIGHT + (n_rows - 1) * NODE_VGAP
    top_y = total_h / 2.0
    row_ys = [top_y - i * (NODE_HEIGHT + NODE_VGAP) for i in range(n_rows)]

    # 生成节点代码
    nodes_code_lines = []
    node_ids = []
    for col_idx, col in enumerate(COLUMNS):
        cx = centers_x[col_idx]
        col_ids = []
        for row_idx, node in enumerate(col.nodes):
            y = row_ys[row_idx]
            nid = f"n{col_idx}_{row_idx}"
            col_ids.append(nid)
            text_w = node.width_cm - 0.4  # text width 略小于 node width
            nodes_code_lines.append(
                f"\\node[cell, minimum width={fmt(node.width_cm)}cm, text width={fmt(text_w)}cm] "
                f"({nid}) at ({fmt(cx)},{fmt(y)}) {{{tex_escape(node.text)}}};"
            )
        node_ids.append(col_ids)

    # 生成 panel 代码：用 fit 包络每列节点，放在 background layer（避免覆盖节点）
    panels_code_lines = []
    panels_code_lines.append(r"\begin{scope}[on background layer]")
    for col_idx, col in enumerate(COLUMNS):
        ids = node_ids[col_idx]
        fit_nodes = " ".join(f"({nid})" for nid in ids)
        pid = f"panel{col_idx}"
        panels_code_lines.append(
            f"\\node[draw=black, line width={col.penwidth}pt, rounded corners=4pt, "
            f"fill={col.fill}, inner sep={fmt(PANEL_PAD)}cm, fit={fit_nodes}] "
            f"({pid}) {{}};"
        )
    panels_code_lines.append(r"\end{scope}")
    # 标题放在各自 panel 左上角上方，左对齐，避免三列标题互相覆盖
    for col_idx, col in enumerate(COLUMNS):
        pid = f"panel{col_idx}"
        panels_code_lines.append(
            f"\\node[title] at ([yshift=2pt]{pid}.north west) {{{tex_escape(col.title)}}};"
        )

    # 生成边代码
    edges_code_lines = []
    # 列内竖向箭头
    for col_idx in range(len(COLUMNS)):
        for row_idx in range(n_rows - 1):
            a = node_ids[col_idx][row_idx]
            b = node_ids[col_idx][row_idx + 1]
            edges_code_lines.append(f"\\draw[arrow] ({a}.south) -- ({b}.north);")

    # 跨栏水平箭头：放在最底行（row_idx = n_rows-1）节点之间
    bottom = n_rows - 1
    # s -> m
    edges_code_lines.append(
        f"\\draw[arrow] ({node_ids[0][bottom]}.east) -- ({node_ids[1][bottom]}.west) "
        f"node[midway, above=18pt, smalllabel] {{案情输入}};"
    )
    # m -> d
    edges_code_lines.append(
        f"\\draw[arrow] ({node_ids[1][bottom]}.east) -- ({node_ids[2][bottom]}.west) "
        f"node[midway, above=18pt, smalllabel] {{候选结果}};"
    )

    # 审计条：在 panel 下方居中
    left_x = centers_x[0] - COLUMNS[0].nodes[0].width_cm / 2.0 - PANEL_PAD
    right_x = centers_x[-1] + COLUMNS[-1].nodes[0].width_cm / 2.0 + PANEL_PAD
    bar_w = right_x - left_x + BAR_EXTRA_W
    bar_x = (left_x + right_x) / 2.0
    bar_y = row_ys[-1] - NODE_HEIGHT / 2.0 - PANEL_PAD - BAR_VGAP - BAR_HEIGHT / 2.0

    bar_text_w = bar_w - 0.4
    edges_code_lines.append(
        f"\\node[bar, minimum width={fmt(bar_w)}cm, text width={fmt(bar_text_w)}cm] "
        f"(audit) at ({fmt(bar_x)},{fmt(bar_y)}) "
        f"{{审计日志 → 加权评价量表 + 思政 / 伦理映射 → 回流“研—训—评”}};"
    )

    # 决策记录：d3 -> audit（标签放在箭头左侧偏上，避免贴 audit）
    edges_code_lines.append(
        f"\\draw[arrow] ({node_ids[2][bottom]}.south) -- ({node_ids[2][bottom]}.south |- audit.north) "
        f"node[pos=0.35, left=6pt, smalllabel] {{决策记录}};"
    )

    # 评价/反思回流：audit 左侧 -> 左弯 -> s3 左侧
    turn_x = left_x - 0.85
    label_x = turn_x + 0.15
    label_y = (bar_y + row_ys[-1]) / 2.0
    edges_code_lines.append(
        f"\\coordinate (turnL) at ({fmt(turn_x)},{fmt(bar_y)});\n"
        f"\\coordinate (turnUp) at ({fmt(turn_x)},{fmt(row_ys[-1])});\n"
        f"\\draw[dasharrow] (audit.west) -- (turnL) -- (turnUp) -- ({node_ids[0][bottom]}.west);\n"
        f"\\node[smalllabel, anchor=west] at ({fmt(label_x)},{fmt(label_y)}) {{评价/反思回流}};"
    )
    # 注意上面标签位置表达式在 f-string 里要处理，简化：
    # 改为放在 turnL 与 turnUp 之间的中点偏右

    # 重写反馈标签，避免复杂 f-string 嵌套
    label_y = (bar_y + row_ys[-1]) / 2.0
    edges_code_lines[-1] = (
        f"\\coordinate (turnL) at ({fmt(turn_x)},{fmt(bar_y)});\n"
        f"\\coordinate (turnUp) at ({fmt(turn_x)},{fmt(row_ys[-1])});\n"
        f"\\draw[dasharrow] (audit.west) -- (turnL) -- (turnUp) -- ({node_ids[0][bottom]}.west);\n"
        f"\\node[smalllabel, anchor=west] at ({fmt(turn_x + 0.1)},{fmt(label_y)}) {{评价/反思回流}};"
    )

    # 汇总替换
    text_w = NODE_HEIGHT  # 占位，实际按节点单独 text width
    # 模板里 %(node_w)s 等用中列节点宽作为代表
    tex = TEX_TEMPLATE % {
        "node_w": fmt(COLUMNS[1].nodes[0].width_cm),
        "node_h": fmt(NODE_HEIGHT),
        "text_w": fmt(COLUMNS[1].nodes[0].width_cm - 0.4),
        "bar_w": fmt(bar_w),
        "bar_h": fmt(BAR_HEIGHT),
        "bar_text_w": fmt(bar_text_w),
        "nodes_code": "\n".join(nodes_code_lines),
        "panels_code": "\n".join(panels_code_lines),
        "edges_code": "\n".join(edges_code_lines),
    }

    out_tex = os.path.join(os.path.dirname(__file__), "fig_workflow.tex")
    with open(out_tex, "w", encoding="utf-8") as f:
        f.write(tex)
    print(f"Wrote {out_tex}")

if __name__ == "__main__":
    main()
